language: php
os: linux
dist: trusty

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - nightly
  - hhvm

jobs:
    include:
        - php: 5.2
          dist: precise
        - php: 5.3
          dist: precise
    allow_failures:
        - php: nightly
        - php: hhvm
        - php: 7.2
        - php: 5.6
        - php: 5.5
        - php: 5.4
        - php: 5.3
        - php: 5.2

install:
    # remove composer lock to allow installing env specific versions
    - rm -f composer.lock
    # flags to pass to install
    - flags="--prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
    # install dependencies using system provided composer binary
    - if php -r "die(+(version_compare(PHP_VERSION,'5.5')!=1));"; then composer install $flags; else composer dump-autoload; fi
    # Remove some tools not required for testing
    - composer remove --dev apigen/apigen

script: phpunit tests/

cache:
    directories:
        - $HOME/.composer/cache
